<?php

namespace Database\Seeders;

use App\Models\Product;
use Database\Factories\ProductFactory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $idColumn = 'id';
        $nameColumn = 'name';
        $descriptionColumn = 'description';

        $products_information = [
            [$idColumn => 1, $nameColumn => 'Neo Pixel Stick', $descriptionColumn => 'Een NeoPixel-stick is een programmeerbare LED-strip die bestaat uit meerdere individuele NeoPixel-LED s die op een enkele printplaat zijn gemonteerd. Elk van deze LEDs kan individueel worden aangestuurd om verschillende kleuren en helderheden te produceren, waardoor een breed scala aan lichteffecten en patronen mogelijk is. De stick wordt vaak gebruikt in doe-het-zelf-elektronica-projecten, zoals decoratieve verlichting, kostuumaccessoires en artistieke installaties. De NeoPixel-stick kan worden aangestuurd via een microcontroller, zoals de Arduino, en vereist doorgaans een voedingsbron om goed te functioneren.'],
            [$idColumn => 2, $nameColumn => 'Neo Pixel', $descriptionColumn => 'NeoPixel is een handelsmerk van Adafruit Industries voor een type programmeerbare RGB-LEDs (rood, groen, blauw) die individueel kunnen worden aangestuurd en geprogrammeerd. NeoPixels zijn verkrijgbaar in verschillende vormen, zoals strips, ringen, matrices en losse LEDs. Ze worden vaak gebruikt in doe-het-zelf-elektronica-projecten en artistieke installaties om kleurrijke lichteffecten te produceren. NeoPixels kunnen worden aangestuurd door een microcontroller, zoals de Arduino, en hebben meestal een aparte voedingsbron nodig om goed te functioneren vanwege hun hoge stroomverbruik. De NeoPixel-bibliotheek van Adafruit maakt het gemakkelijk om de LEDs te programmeren en aan te sturen met behulp van populaire programmeertalen zoals C++, Python en CircuitPython.'],
            [$idColumn => 3, $nameColumn => 'LED Matrix', $descriptionColumn => 'Een LED-matrix is een rechthoekige rangschikking van vele kleine LEDs die individueel kunnen worden aangestuurd om verschillende patronen en afbeeldingen te produceren. LED-matrixen worden vaak gebruikt voor visuele displays en borden in openbare ruimtes, zoals op luchthavens, stations en stadions, maar ze worden ook steeds populairder in doe-het-zelf-elektronica-projecten. LED-matrixen zijn verkrijgbaar in verschillende maten en configuraties, variërend van kleine 8x8-matrixen tot grote matrixen van 64x64 of zelfs groter. Ze worden aangestuurd door een microcontroller, zoals de Arduino, die de LEDs programmeert om te knipperen, flikkeren of andere effecten te produceren. Er zijn verschillende bibliotheken beschikbaar voor het programmeren van LED-matrixen, waaronder de Adafruit GFX-bibliotheek en de FastLED-bibliotheek.'],
            [$idColumn => 4, $nameColumn => 'Bodemvochtigheids sensor', 'stock' => 100, $descriptionColumn => 'Een bodemvochtigheidssensor is een sensor die wordt gebruikt om het vochtgehalte van de grond te meten. De sensor bestaat uit twee elektroden die in de grond worden gestoken en die een elektrische stroom tussen zich door laten lopen. Wanneer de grond vochtig is, kan de elektrische stroom gemakkelijk door de grond stromen en wordt een hogere geleidbaarheid gemeten. Als de grond droger wordt, neemt de geleidbaarheid af en wordt een lager vochtgehalte gemeten. De metingen van de sensor worden omgezet in een analoog of digitaal signaal dat kan worden gelezen door een microcontroller, zoals de Arduino, en kunnen worden gebruikt om geautomatiseerde besproeiingssystemen aan te sturen. Bodemvochtigheidssensoren zijn handig voor het handhaven van de optimale vochtigheidsniveaus voor planten en het verminderen van waterverspilling.'],
            [$idColumn => 5, $nameColumn => 'time-of-light distance sensor', $descriptionColumn => 'Een time-of-flight (ToF) afstandssensor is een sensor die wordt gebruikt om de afstand tot een object te meten door het meten van de tijd die licht nodig heeft om van de sensor naar het object en terug te reizen. De sensor stuurt een korte puls van infrarood licht uit en meet vervolgens hoe lang het duurt voordat het licht terugkomt. De tijd die nodig is voor het licht om heen en terug te reizen wordt omgezet in een afstandsmeting. ToF-sensoren worden vaak gebruikt in robotica, drones, en andere automatiseringstoepassingen waarbij nauwkeurige afstandsmeting vereist is. De sensoren kunnen worden aangestuurd door een microcontroller, zoals de Arduino, en hebben meestal een digitale of analoge uitgang om de gemeten afstandswaarde te communiceren. ToF-sensoren hebben het voordeel dat ze zeer nauwkeurig zijn en werken bij verschillende lichtomstandigheden, waardoor ze ideaal zijn voor toepassingen in zowel binnen- als buitenomgevingen.'],
            [$idColumn => 6, $nameColumn => '12Volt speaker', $descriptionColumn => 'Een 12-volts speaker is een luidspreker die werkt op 12 volt gelijkstroom (DC) in plaats van de standaard 120 volt wisselstroom (AC) die wordt gebruikt in huishoudelijke stroomnetten. Dit maakt het ideaal voor gebruik in mobiele toepassingen, zoals autos, boten, campers en andere voertuigen. De 12-volts speaker wordt vaak aangestuurd door een versterker die is ontworpen voor gebruik in voertuigen en die meestal wordt gevoed door de accu van het voertuig. Het vermogen van de speaker wordt meestal uitgedrukt in watts, en hoe hoger het wattage, hoe luider en krachtiger het geluid kan zijn. 12-volts speakers zijn verkrijgbaar in verschillende maten, vormen en stijlen, van kleine tweeters tot grote subwoofers. Ze worden vaak gebruikt in autos en andere voertuigen om muziek af te spelen en geluidseffecten te produceren.'],
            [$idColumn => 7, $nameColumn => 'MP3 Speler', $descriptionColumn => 'Een MP3-speler is een draagbaar elektronisch apparaat dat wordt gebruikt om digitale audio-bestanden af te spelen in het MP3-formaat. MP3-spelers zijn verkrijgbaar in verschillende maten en vormen, variërend van kleine draagbare spelers tot grotere apparaten met meer geavanceerde functies. MP3-spelers hebben meestal een intern geheugen waarop de gebruiker digitale audiobestanden kan opslaan en afspelen, en sommige modellen hebben ook een uitbreidbaar geheugen via een SD-kaart of andere geheugenkaart. De meeste MP3-spelers hebben een LCD-scherm waarop de gebruiker informatie over de afgespeelde audiobestanden kan bekijken, zoals de naam van het nummer, de artiest en het album. MP3-spelers kunnen worden aangesloten op een computer via een USB-kabel om audiobestanden over te zetten vanaf de computer naar de speler. Sommige MP3-spelers hebben ook extra functies, zoals radio, Bluetooth-connectiviteit, en spraakopname.'],
            [$idColumn => 8, $nameColumn => 'XBEE', $descriptionColumn => 'Een XBee is een serie draadloze radiozenders en -ontvangers die worden gebruikt om draadloze communicatie te bieden tussen microcontrollers, computers en andere apparaten. XBee-modules zijn verkrijgbaar in verschillende frequenties, variërend van 2,4 GHz tot 900 MHz, en hebben meestal een bereik van enkele honderden meters tot enkele kilometers, afhankelijk van de frequentie en omgevingsfactoren. De XBee-modules werken met een seriële communicatie-interface en worden vaak gebruikt in doe-het-zelf-elektronica-projecten om draadloze communicatie mogelijk te maken tussen verschillende apparaten, zoals sensoren, microcontrollers en computers. XBee-modules hebben een aantal verschillende modi en configuratieopties die kunnen worden geprogrammeerd met behulp van de XBee-API of de AT-commandos. XBee-modules worden ook vaak gebruikt in industriële automatisering, afstandsbediening en telemetriesystemen, en bieden een betrouwbare en eenvoudige oplossing voor draadloze communicatie.'],
            [$idColumn => 9, $nameColumn => '12mm drukknop verlicht', $descriptionColumn => 'Een 12mm drukknop met verlichting is een schakelaar die wordt gebruikt om een elektrische verbinding te openen of te sluiten wanneer erop wordt gedrukt. De drukknop heeft een diameter van 12 millimeter en is meestal uitgerust met een LED-lampje dat oplicht wanneer de schakelaar wordt ingedrukt. De verlichting kan worden gebruikt om aan te geven of de schakelaar is ingeschakeld of om een visueel effect toe te voegen aan een doe-het-zelf-elektronica-project. De 12mm drukknop met verlichting kan worden aangesloten op een circuit met behulp van draden of een printplaat, en wordt meestal gevoed door een 5 of 12 volt DC-voeding. De drukknop met verlichting is verkrijgbaar in verschillende kleuren, zoals rood, groen, blauw en geel, en kan worden gebruikt in verschillende toepassingen, zoals elektronica-reparaties, doe-het-zelf-elektronica-projecten, spelcomputers en audio-apparatuur.'],
            [$idColumn => 10, $nameColumn => 'Raspberry Pi 3', $descriptionColumn => 'De Raspberry Pi 3 is een kleine, single-board computer die wordt gebruikt voor educatieve en hobbyistische doeleinden en als onderdeel van verschillende doe-het-zelf-elektronica-projecten. De Raspberry Pi 3 heeft een 1,2 GHz quad-core ARM-processor en 1 GB RAM-geheugen. Het apparaat heeft verschillende aansluitmogelijkheden, waaronder vier USB-poorten, een HDMI-poort, een ethernetpoort en een 3,5 mm audio jack. Het kan worden gevoed door een 5V micro-USB-voedingsadapter en heeft een microSD-kaartsleuf voor opslag van het besturingssysteem en andere gegevens. De Raspberry Pi 3 kan worden gebruikt voor verschillende taken, zoals het draaien van een webserver, het bouwen van een mediaspeler, het maken van een thuisautomatiseringssysteem of het programmeren van hardwareprojecten. Het apparaat ondersteunt verschillende besturingssystemen, waaronder de Raspbian OS, Ubuntu en Windows 10 IoT Core. Het heeft ook een groot aantal ontwikkelingstools en bibliotheken beschikbaar, waaronder Python en Scratch, die het gemakkelijk maken om te beginnen met programmeren en experimenteren met hardware.'],
            [$idColumn => 11, $nameColumn => 'Powerbank', $descriptionColumn => 'Een powerbank is een draagbare batterij die wordt gebruikt om mobiele apparaten op te laden wanneer er geen stopcontact in de buurt is. Een powerbank heeft een interne oplaadbare batterij en is voorzien van een of meerdere USB-poorten waarop de mobiele apparaten kunnen worden aangesloten voor het opladen. Powerbanks zijn verkrijgbaar in verschillende maten, capaciteiten en uitvoeringen en kunnen worden opgeladen via een micro-USB-kabel of een USB-C-kabel. Sommige powerbanks hebben extra functies, zoals een zaklamp, zonnepanelen of draadloos opladen.  Powerbanks zijn handig voor mensen die veel onderweg zijn en hun mobiele apparaten willen opladen zonder afhankelijk te zijn van een stopcontact. Ze zijn geschikt voor het opladen van verschillende apparaten, zoals smartphones, tablets, draagbare luidsprekers, draadloze oortjes en smartwatches. De capaciteit van een powerbank wordt gemeten in mAh (milliampère-uur) en geeft aan hoeveel energie de powerbank kan leveren voordat hij zelf moet worden opgeladen. Hoe hoger de capaciteit van de powerbank, hoe meer keer een mobiel apparaat kan worden opgeladen voordat de powerbank zelf moet worden opgeladen.'],
            [$idColumn => 12, $nameColumn => 'Transmissie motor', $descriptionColumn => 'Een transmissiemotor is een type motor waarbij het vermogen wordt overgedragen van de motor naar de wielen via een transmissie. De transmissie zorgt voor verschillende overbrengingsverhoudingen om de kracht en snelheid van de motor overeen te laten komen met de vereisten van de bestuurder en de rijomstandigheden. Dit betekent dat de motor meer koppel kan leveren bij lage snelheden en een hoger vermogen bij hoge snelheden, waardoor de efficiëntie en prestaties van de motor worden verbeterd. Een transmissiemotor wordt vaak gebruikt in voertuigen met een verbrandingsmotor, zoals autos en motorfietsen, maar kan ook worden gebruikt in elektrische voertuigen om de prestaties van de motor te verbeteren. Er zijn verschillende soorten transmissies die kunnen worden gebruikt, waaronder handgeschakelde transmissies, automatische transmissies en continu variabele transmissies (CVTs). Elk type transmissie heeft zijn eigen voor- en nadelen op het gebied van efficiëntie, prestaties en gebruiksgemak.'],
            [$idColumn => 13, $nameColumn => 'Servo Motor', $descriptionColumn => 'Een servo motor is een type elektromotor dat wordt gebruikt voor het regelen van beweging en positie. Het bestaat uit een motor, een vertragingsmechanisme en een feedbacksysteem dat de positie van de motor regelt. Servo motoren worden vaak gebruikt in doe-het-zelf-elektronica-projecten, zoals robotica, RC-voertuigen en drones, om beweging, richting en positie te regelen.Een servo motor kan worden aangestuurd door een signaal van een microcontroller, zoals de Arduino. Het signaal stuurt een pulsbreedtemodulatie (PWM) signaal naar de servo motor, wat de positie van de motor bepaalt. Door de pulsbreedte van het signaal te veranderen, kan de positie van de servo motor worden aangepast. Het feedbacksysteem in de servo motor zorgt ervoor dat de motor de gewenste positie bereikt en behoudt. Servo motoren zijn verkrijgbaar in verschillende maten en vermogens, en kunnen worden aangepast aan de specifieke eisen van een project. Ze zijn betrouwbaar, nauwkeurig en gemakkelijk te gebruiken, en worden vaak gebruikt in verschillende toepassingen, zoals automatiseringssystemen, bewakingscameras, positioneringssystemen, en industriële robots.'],
            [$idColumn => 14, $nameColumn => 'USB hub', $descriptionColumn => 'Een USB-hub is een apparaat dat wordt gebruikt om meerdere USB-apparaten aan te sluiten op één USB-poort op een computer of ander apparaat. Een USB-hub breidt de connectiviteit van een apparaat uit door extra USB-poorten beschikbaar te stellen. Het apparaat wordt aangesloten op een computer of ander apparaat met een enkele USB-kabel en biedt vervolgens extra USB-poorten waarop andere USB-apparaten kunnen worden aangesloten, zoals een muis, toetsenbord, printer, camera, USB-stick of andere randapparatuur.'],
            [$idColumn => 15, $nameColumn => 'Arduino Mega', $descriptionColumn => 'De Arduino Mega is een microcontroller board gebaseerd op de ATmega2560 microcontroller. Het board beschikt over 54 digitale I/O-pinnen, waarvan 15 pinnen PWM-output ondersteunen, 16 analoge ingangen en 4 UARTs (seriële poorten). Het board heeft ook een 16 MHz kristaloscillator, een USB-verbinding, een power jack, een ICSP-header en een resetknop.'],
            [$idColumn => 16, $nameColumn => 'Arduino MKR1000', $descriptionColumn => 'De Arduino MKR1000 is een microcontroller board dat is ontworpen voor het internet of things (IoT) en is gebaseerd op de Atmel SAMD21 ARM Cortex-M0+ microcontroller en de ATWINC1500 Wi-Fi module. Het board beschikt over 14 digitale I/O-pinnen en 6 analoge ingangen. Het board heeft ook een 32-bit ARM Cortex-M0+ core, 256 KB flash geheugen, 32 KB SRAM en ondersteunt 2,4 GHz Wi-Fi-connectiviteit.De Arduino MKR1000 is ontworpen voor projecten die een draadloze internetverbinding vereisen en is geschikt voor IoT-projecten. Het board heeft een laag stroomverbruik en kan worden gevoed via een USB-aansluiting of een 3,7 V Li-Po-batterij. Het board is compatibel met de Arduino IDE en kan worden geprogrammeerd met behulp van C/C++.'],
            [$idColumn => 17, $nameColumn => 'Arduino Uno', $descriptionColumn => 'De Arduino Uno is een microcontroller board dat is gebaseerd op de ATmega328P microcontroller. Het board beschikt over 14 digitale I/O-pinnen, waarvan 6 pinnen PWM-output ondersteunen, 6 analoge ingangen en een 16 MHz kristaloscillator. Het board heeft ook een USB-verbinding, een power jack, een ICSP-header en een resetknop.'],
            [$idColumn => 18, $nameColumn => 'Arduino Nano', $descriptionColumn => 'De Arduino Nano is ontworpen voor projecten die een kleinere en compacte board vereisen dan de Arduino Uno. Het board kan worden geprogrammeerd met behulp van de Arduino IDE en is compatibel met verschillende shields (uitbreidingsmodules) die beschikbaar zijn voor de Arduino-boards.'],
            [$idColumn => 19, $nameColumn => 'KNOPPEN', $descriptionColumn => 'Knoppen zijn elektronische componenten die worden gebruikt om een elektrische stroom te onderbreken of te activeren wanneer ze worden ingedrukt. Ze worden vaak gebruikt in doe-het-zelf-elektronica-projecten om apparaten in en uit te schakelen, modi te wijzigen, parameters te regelen en andere functies te activeren. Er zijn verschillende soorten knoppen beschikbaar, waaronder drukknoppen, tuimelschakelaars, schuifschakelaars en roterende knoppen.Drukknoppen zijn de meest voorkomende vorm van knoppen en worden geactiveerd wanneer er druk op wordt uitgeoefend. Ze zijn verkrijgbaar in verschillende maten, vormen en kleuren en worden vaak gebruikt in toetsenborden, afstandsbedieningen en andere elektronische apparaten.'],
            [$idColumn => 20, $nameColumn => 'IR afstand sensor', $descriptionColumn => 'IR afstand sensoren worden vaak gebruikt in robotica, drones, en andere elektronica-projecten om obstakels te detecteren en te vermijden, en om de afstand tot een object te meten. Deze sensoren zijn verkrijgbaar in verschillende formaten en modellen, waaronder enkelvoudige sensoren en sensoren met een array van detectoren.'],
        ];

        // use the products_information array to create the products with the ProductFactory
        foreach ($products_information as $product_information) {
            ProductFactory::new()->create($product_information);
        }

    }
}
